[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC", "Zlib", "Unicode-3.0"]

[advisories]
ignore = []

[bans]
multiple-versions = "warn"

[[bans.deny]]
name = "openssl"

[[bans.deny]]
name = "openssl-sys"

[[bans.deny]]
name = "native-tls"

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
